services:
  - type: web
    name: onlineshop-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: onlineshop-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    plan: free
    envVars:
      - key: REACT_APP_API_BASE
        value: https://onlineshop-backend.onrender.com
